### ISSUE TITLE
Dependancy needs to be updated

### ISSUE THREAD

**Issue by menkaur** [mbaraa/mbaraa-overlay#1]
in the ebuild file, you write:
BDEPEND="
	>=dev-go/go-1.19:1
"

should be dev-lang/go

**Comment by mbaraa** [comment]
I think with `>=` it should work with any newer go version.

**Comment by mbaraa** [comment]
Oopsie, I spent like 30mins to notice that they had changed `dev-go` to `dev-lang` :eyes:
Thanks mate!
